- name: Install packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items: "{{ packages | default([]) }}"

- name: Create directory for docker-compose.yml
  file:
    path: /opt/docker
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: "/docker/docker-compose.yml"
    dest: /opt/docker/docker-compose.yml

- name: Deploy services with Docker Compose
  shell: docker-compose up -d
  args:
    chdir: /opt/docker
